---
title: "AV NucSeq Filtering"
author: "SAR"
date: "20200626"
editor_options: 
  chunk_output_type: inline
---
#Load packages
```{r}

library(Seurat)
library(ggplot2)
library(dplyr)
library(viridis)

options(future.globals.maxSize = 5000 * 1024^2)

```

#Load AV Nucleus data into R
```{r}
ids <- c("AV")

d10x.data <- sapply(ids, function(i){
  d10x <- Read10X("/data4/svz_10x/pipestance_final_non-forced/AV/outs/filtered_gene_bc_matrices/GRCm38/")
  colnames(d10x) <- paste(sapply(strsplit(colnames(d10x),split="-"),'[[',1L),i,sep="-")
  d10x
})

experiment.data <- do.call("cbind", d10x.data)

AV_nuclei <- CreateSeuratObject(
  experiment.data,
  project = "AV_NucSeq", 
  min.cells = 10,
  names.field = 2,
  names.delim = "\\-")

AV_nuclei
```
#Percent Mito
```{r}
AV_nuclei[["percent.mt"]] <- PercentageFeatureSet(AV_nuclei, pattern = "^mt-")
```

#filtering mitochondrial genes
```{r}

hist(AV_nuclei@meta.data$percent.mt)
quantM <- quantile(AV_nuclei@meta.data$percent.mt)
quantM

AV_nuclei <- SubsetData(AV_nuclei,
  subset.name = c("percent.mt"),
  low.threshold  = 0,
  high.threshold = 10)

hist(AV_nuclei@meta.data$percent.mt)
quantM <- quantile(AV_nuclei@meta.data$percent.mt)
quantM
```

#filtering ncounts
```{r}
hist(AV_nuclei@meta.data$nCount_RNA)
quantsC <- quantile(AV_nuclei@meta.data$nCount_RNA)
quantsC
countscutoff <- quantile(AV_nuclei@meta.data$nCount_RNA, c(.05, .95))

AV_nuclei <- SubsetData(AV_nuclei,
  subset.name = c("nCount_RNA"),
  low.threshold  = countscutoff[1],
  high.threshold = countscutoff[2])
```

#filtering nFeats
```{r}
hist(AV_nuclei@meta.data$nFeature_RNA)
quantG <- quantile(AV_nuclei@meta.data$nFeature_RNA)
quantG
featscutoff <- quantile(AV_nuclei@meta.data$nFeature_RNA, c(.05, .95))

AV_nuclei <- SubsetData(AV_nuclei,
  subset.name = c("nFeature_RNA"),
  low.threshold  = featscutoff[1])


AV_nuclei

```

#SCTransfrom, Cluster
```{r}
AV_nuclei <- SCTransform(AV_nuclei)
AV_nuclei

AV_nuclei<- RunPCA(AV_nuclei, verbose = T, npcs = 100)
PCAPlot(object = AV_nuclei, dims=c(1,2) )
ElbowPlot(AV_nuclei, ndims = 100)

```

#UMAP and plot
```{r}
AV_nuclei <- FindNeighbors(AV_nuclei, dims = 1:50, verbose = FALSE)
AV_nuclei <- FindClusters(AV_nuclei, resolution = c(0.8, seq(0.5, 2, 0.5)), verbose = FALSE)

AV_nuclei <- RunUMAP(AV_nuclei, dims = 1:50)


DimPlot(AV_nuclei,group.by="SCT_snn_res.2", pt.size = 0.4, label = T)
ggsave(paste("AV_NucSeq_DimPlot_",format(Sys.time(), "%Y-%m-%d_%H-%M"), ".png", sep = ""), width = 6, height = 4, units = "in", dpi=300)
```



```{r}
saveRDS(AV_nuclei, file = paste("AV_NucSeq_sctransformed_",format(Sys.time(), "%Y-%m-%d_%H-%M"), ".rds", sep = ""))

```
