---
title: "Filtering and QC"
output: html_notebook
---
#setup
```{r}
load("/data4/marcos/WC - Mouse 2020/deMultiplex/WC_sctransformed_demultiplexed_2020-05-01.Rdata")
setwd("/data4/marcos/WC - Mouse 2020/Filtering and QC")
```

#Removing doublets detected on demultiplex 
```{r} 
#Bar1 and Bar2 are males/p35
#Bar 3 and 4, females/p29
Idents(experiment.deMPx) <- "MULTI"
experiment.deMPx2 <- subset(experiment.deMPx, idents = c("Bar1", "Bar2", "Bar3", "Bar4", "Negative"))
```

#filtering mitochondrial genes
```{r}
#All the filtering steps can be done in a single line of code:
# Seurat.Obj.filtered <- subset(Seurat.Obj, subset = nFeature_RNA > 200 & nFeature_RNA < 7000 & percent.mt < 5)

hist(experiment.deMPx2@meta.data$percent.mt)
quantM <- quantile(experiment.deMPx2@meta.data$percent.mt)
quantM

experiment.deMPx_filt <- SubsetData(experiment.deMPx2,
  subset.name = c("percent.mt"),
  low.threshold  = 0,
  high.threshold = 10)

hist(experiment.deMPx_filt@meta.data$percent.mt)
quantM <- quantile(experiment.deMPx_filt@meta.data$percent.mt)
quantM
```

#filtering ncounts
```{r}
hist(experiment.deMPx_filt@meta.data$nCount_RNA)
quantsC <- quantile(experiment.deMPx_filt@meta.data$nCount_RNA)
quantsC
countscutoff <- quantile(experiment.deMPx_filt@meta.data$nCount_RNA, c(.05, .95))

experiment.deMPx_filt <- SubsetData(experiment.deMPx_filt,
  subset.name = c("nCount_RNA"),
  low.threshold  = countscutoff[1],
  high.threshold = countscutoff[2])
```
#filtering nFeats
```{r}
hist(experiment.deMPx_filt@meta.data$nFeature_RNA)
quantG <- quantile(experiment.deMPx_filt@meta.data$nFeature_RNA)
quantG
featscutoff <- quantile(experiment.deMPx_filt@meta.data$nFeature_RNA, c(.05, .95))

experiment.deMPx_filt <- SubsetData(experiment.deMPx_filt,
  subset.name = c("nFeature_RNA"),
  low.threshold  = featscutoff[1])

```

```{r}
DimPlot(experiment.deMPx_filt)

Idents(experiment.deMPx_filt) <- "seurat_clusters"
save(experiment.deMPx_filt, file = paste0("experiment.deMPx_filt_", Sys.Date(), ".Rdata"))

#v.2020-05-04: filtered cells with >5% mitochondrial genes
#v.2020-05-13: filtered cells with >10% mitochondrial genes
```



