---
title: "Revision Analyses"
output: html_notebook
author: SAR
---


#Load libraries and datasets
```{r}
library(Seurat)
library(ggplot2)
library(viridis)
library(dplyr)
library(patchwork)
library(grid)
#install.packages('writexl')
library(writexl)



options(future.globals.maxSize = 5000 * 1024^2)

#Load whole cell scRNA-Seq Dataset
scSeq <- readRDS('publication_objects/scSeq.rds')


DimPlot(scSeq, label=T)

```

#Percent B cell/Astrocyte marker expression & Average expression calculations
```{r}
#From: https://github.com/satijalab/seurat/issues/371 30 March 2021

PrctCellExpringGene <- function(object, genes, group.by = "all"){
    if(group.by == "all"){
        prct = unlist(lapply(genes,calc_helper, object=object))
        result = data.frame(Markers = genes, Cell_proportion = prct)
        return(result)
    }

    else{        
        list = SplitObject(object, group.by)
        factors = names(list)

        results = lapply(list, PrctCellExpringGene, genes=genes)
        for(i in 1:length(factors)){
        results[[i]]$Feature = factors[i]
        }
        combined = do.call("rbind", results)
        return(combined)
    }
}

calc_helper <- function(object,genes){
    counts = object[['SCT']]@counts
    ncells = ncol(counts)
    if(genes %in% row.names(counts)){
    sum(counts[genes,]>0)/ncells
    }else{return(NA)}
}

DimPlot(scSeq, group.by = "Cell_Type")
pct_exp <-PrctCellExpringGene(scSeq ,genes =c("Gfap","GFP", "S100a6", "Slc1a3", "Thbs4"), group.by = "Cell_Type")
pct_exp


avg_exp <- AverageExpression(scSeq, features=c("Gfap","GFP", "S100a6", "Slc1a3", "Thbs4"), group.by = "Cell_Type" )
avg_exp$SCT


DotPlot(scSeq, features=c("Gfap","GFP", "S100a6", "Slc1a3", "Thbs4"), group.by = "Cell_Type")
DotPlot(scSeq, features=c("Gfap","GFP", "S100a6", "Slc1a3", "Thbs4"), group.by = "Cell_Type", col.min = 0)
```

#Percent A cell predicted region per cluster calculation
```{r}
scSeq.A <- subset(scSeq, idents=c(0,1,4,6))

summ <- scSeq.A@meta.data %>% group_by(integrated_snn_res.1.5) %>% count(Predicted_Region_Acells)
summ



```


#Counts & Percent S & G2M cells per cluster
```{r}
scSeq <- readRDS('publication_objects/scSeq.rds')


clusterPhase <- scSeq@meta.data %>%
  group_by(integrated_snn_res.1.5, Phase) %>%
  summarise(n = n()) %>%
  mutate(Percent = round(n / sum(n)*100, 2))
colnames(clusterPhase)[1] <- "Cluster"

clusterPhase

write_xlsx(clusterPhase, path = "/Supplementary_Table_ClusterPhaseSummary.xlsx")

```